## Fake News Classifier Using LSTM

Dataset: https://www.kaggle.com/c/fake-news/data#

In [1]:
import pandas as pd

In [4]:
df=pd.read_csv('train1.csv')

In [5]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [6]:
df.shape

(20800, 5)

In [7]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [8]:
df.isnull().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [ ]:
##since in total 20k records are there and only 2.2k records have null values and in that case
we can use dropNaN values feature

In [9]:
###Drop Nan Values
df=df.dropna()


In [10]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [11]:
## Get the Independent Features

X=df.drop('label',axis=1)

In [12]:
## Get the Dependent features
y=df['label']

In [13]:
X.shape

(18285, 4)

In [14]:
y.shape

(18285,)

In [15]:
import tensorflow as tf

In [16]:
tf.__version__

'2.6.2'

In [19]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import LSTM
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [20]:
### Vocabulary size
voc_size=5000

### Onehot Representation

In [21]:
messages=X.copy()

In [22]:
messages['title'][1]

'FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart'

In [24]:
messages['title'][2]

'Why the Truth Might Get You Fired'

In [23]:
messages

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      Ever get the feeling your life circles the rou...  
2      Why the Truth Might Get You Fired October 29, ...  
3      Videos 15 Civilians Killed In Single US Airstr...  
4      Print \nAn Iranian woman has been sentenced to...  
...                                                  ...  
20795  Rapper T. I. unloaded on black celebrities who...  
20796  When the Green Bay Packers lost to the Washing...  
20797  The Macy’s of today grew from the union of sev...  
20798  NATO, Russia To Hold Parallel Exercises In Bal...  
20799    David Swanson is an author, activist, journa...  

[18285 rows x 4 columns]

In [25]:
messages.reset_index(inplace=True)

In [26]:
messages

index     id                                              title  \
0          0      0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1      1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2      2                  Why the Truth Might Get You Fired   
3          3      3  15 Civilians Killed In Single US Airstrike Hav...   
4          4      4  Iranian woman jailed for fictional unpublished...   
...      ...    ...                                                ...   
18280  20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
18281  20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
18282  20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
18283  20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
18284  20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
18280                              Jerome Hudson   
18281                           Benjamin Hoffman   
18282  Michael J. de la Merced and Rachel Abrams   
18283                                Alex Ansary   
18284                              David Swanson   

                                                    text  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      Ever get the feeling your life circles the rou...  
2      Why the Truth Might Get You Fired October 29, ...  
3      Videos 15 Civilians Killed In Single US Airstr...  
4      Print \nAn Iranian woman has been sentenced to...  
...                                                  ...  
18280  Rapper T. I. unloaded on black celebrities who...  
18281  When the Green Bay Packers lost to the Washing...  
18282  The Macy’s of today grew from the union of sev...  
18283  NATO, Russia To Hold Parallel Exercises In Bal...  
18284    David Swanson is an author, activist, journa...  

[18285 rows x 5 columns]

In [27]:
import nltk
import re
from nltk.corpus import stopwords

In [28]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\rpart\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [29]:
### Dataset Preprocessing
from nltk.stem.porter import PorterStemmer ##stemming purpose
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [30]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [31]:
corpus[1]

'flynn hillari clinton big woman campu breitbart'

In [32]:
onehot_repr=[one_hot(words,voc_size)for words in corpus] 
onehot_repr

[[1665, 1650, 1789, 376, 335, 4176, 3618, 224, 1037, 4845],
 [2696, 4833, 128, 2363, 2366, 4769, 3930],
 [1626, 1736, 2789, 4400],
 [455, 3356, 896, 2570, 2354, 2953],
 [2496, 2366, 3509, 1197, 2301, 355, 2366, 1145, 4672, 1962],
 [2816,
  410,
  214,
  2428,
  4447,
  2114,
  4345,
  4526,
  1648,
  143,
  4391,
  2925,
  723,
  55,
  3930],
 [43, 1390, 4660, 4522, 3514, 1838, 2318, 2432, 3570, 738, 1356],
 [3751, 517, 3650, 1028, 4657, 2516, 2114, 3988, 3570, 738, 1356],
 [707, 598, 1303, 2997, 1479, 1272, 1792, 2307, 2114, 996],
 [4123, 1337, 1017, 4549, 2374, 1583, 2920, 2121],
 [803, 1432, 4297, 2324, 195, 1930, 156, 3722, 945, 1754, 351],
 [2570, 1831, 335, 1272, 2114, 4657],
 [2249, 877, 86, 2626, 3263, 2609, 3021, 2381, 1977],
 [3062, 1823, 1014, 98, 3548, 4795, 2324, 3570, 738, 1356],
 [3090, 4162, 350, 3577, 2917, 3570, 738, 1356],
 [779, 4007, 1814, 1944, 4838, 3009, 1443, 633, 3759, 4476],
 [3457, 4610, 4833],
 [704, 4496, 123, 3143, 2114, 4460, 1693, 3930],
 [681, 2472, 12

In [33]:
corpus[1]

'flynn hillari clinton big woman campu breitbart'

In [34]:
onehot_repr[1]

[2696, 4833, 128, 2363, 2366, 4769, 3930]

### Embedding Representation

In [35]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='post',maxlen=sent_length)
print(embedded_docs)

[[1665 1650 1789 ...    0    0    0]
 [2696 4833  128 ...    0    0    0]
 [1626 1736 2789 ...    0    0    0]
 ...
 [4969 1918 3908 ...    0    0    0]
 [2503 4657 4673 ...    0    0    0]
 [  78 1009 3530 ...    0    0    0]]


In [36]:
embedded_docs[1]

array([2696, 4833,  128, 2363, 2366, 4769, 3930,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0])

In [37]:
embedded_docs[0]

array([1665, 1650, 1789,  376,  335, 4176, 3618,  224, 1037, 4845,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0])

In [38]:
## Creating model
embedding_vector_features=40 ##features representation
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
##20 is sentence length and 40 is feature representation for each words
model.add(LSTM(100)) ##100 neurons
model.add(Dense(1,activation='sigmoid')) #output layer
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 20, 40)            200000    
_________________________________________________________________
lstm (LSTM)                  (None, 100)               56400     
_________________________________________________________________
dense (Dense)                (None, 1)                 101       
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [39]:
len(embedded_docs),y.shape

(18285, (18285,))

In [40]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [41]:
X_final.shape,y_final.shape

((18285, 20), (18285,))

In [42]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

### Model Training

In [43]:
### Finally Training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
192/192 [==============================] - 6s 17ms/step - loss: 0.3082 - accuracy: 0.8464 - val_loss: 0.2097 - val_accuracy: 0.9102
Epoch 2/10
192/192 [==============================] - 3s 15ms/step - loss: 0.1426 - accuracy: 0.9449 - val_loss: 0.2101 - val_accuracy: 0.9211
Epoch 3/10
192/192 [==============================] - 3s 16ms/step - loss: 0.1039 - accuracy: 0.9599 - val_loss: 0.2560 - val_accuracy: 0.9158
Epoch 4/10
192/192 [==============================] - 3s 16ms/step - loss: 0.0775 - accuracy: 0.9707 - val_loss: 0.2906 - val_accuracy: 0.9128
Epoch 5/10
192/192 [==============================] - 3s 15ms/step - loss: 0.0585 - accuracy: 0.9794 - val_loss: 0.3274 - val_accuracy: 0.9148
Epoch 6/10
192/192 [==============================] - 3s 15ms/step - loss: 0.0399 - accuracy: 0.9862 - val_loss: 0.3749 - val_accuracy: 0.9135
Epoch 7/10
192/192 [==============================] - 3s 15ms/step - loss: 0.0291 - accuracy: 0.9908 - val_loss: 0.4370 - val_accuracy: 0.9085

### Adding Dropout 

In [ ]:
from tensorflow.keras.layers import Dropout
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

### Performance Metrics And Accuracy

In [44]:
y_pred=model.predict(X_test)

In [45]:
y_pred=np.where(y_pred > 0.6, 1,0) ##Condition if is > than 0.6 set it to 1 else 0

##Can use AUC ROC Curve instead

In [46]:
from sklearn.metrics import confusion_matrix

In [47]:
confusion_matrix(y_test,y_pred)

array([[3152,  267],
       [ 304, 2312]], dtype=int64)

In [50]:
confusion_matrix(y_pred,y_test)

array([[3152,  304],
       [ 267, 2312]], dtype=int64)

In [48]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9053852526926264

In [49]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.91      0.92      0.92      3419
           1       0.90      0.88      0.89      2616

    accuracy                           0.91      6035
   macro avg       0.90      0.90      0.90      6035
weighted avg       0.91      0.91      0.91      6035

